# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Dir-Split
version_from: lib/Dir/Split.pm
installdirs:  perl
requires:
    File::Copy:                    0
    File::Path:                    0

distribution_type: module
license: artistic
generated_by: ExtUtils::MakeMaker version 6.16
