--- #YAML:1.0
module_name: Dir-Split
dist_version_from: lib/Dir/Split.pm
installdirs:  site
requires:
    Carp:                          0
    File::Copy:                    0
    File::Path:                    0
recommends:
    Test::More:                    0
distribution_type: module
license: artistic
dist_author: Steven Schubiger
dist_abstract: Splits the files of a directory to subdirectories.
