# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Dir-Split
version:      0.76
version_from: lib/Dir/Split.pm
installdirs:  site
requires:
    Carp:                          0
    File::Basename:                0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    SelfLoader:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
